Feature: Auth using jwt & confirm email
Yaroslaww-1/cte pull request #19
Opened 2021-03-24 21:37 UTC by Yaroslaww-1

Closes #16

2021-03-25 07:40 UTC, nosovk requested changes

2021-03-25 07:40 UTC, nosovk commented on .eslintrc.js
> +    'prettier',
было в чате что лучше так не делать

2021-03-25 07:40 UTC, nosovk commented on backend/src/adapters/mailer/mailer.adapter.ts
> +        user: this.sender,
this.sender - почему он вынесен в отдельныую переменну?
а вторая такая же строка нет?

2021-03-25 07:40 UTC, nosovk commented on backend/src/api/http/modules/auth/auth.controller.ts
> +  @Post('login')
add rate limti

2021-03-25 07:40 UTC, nosovk commented on backend/src/api/http/modules/auth/auth.controller.ts
> +      domain: 'localhost',
it will cause error on production

2021-03-25 07:40 UTC, nosovk commented on backend/src/api/http/modules/auth/auth.controller.ts
> +      maxAge: loginSuccessResponse.refTokenExpiresInSeconds,
у кук есть длина жизни.
Но на самом делел вопрос в другом - куки посылаются при каждом запросе, это значит что рефреш токен у тебя будет слаться при каждом запросе. Что как бы противоречит его назначению

2021-03-25 08:24 UTC, Yaroslaww-1 commented on backend/src/adapters/mailer/mailer.adapter.ts
> +        user: this.sender,
@Fireman9

2021-03-27 12:17 UTC, Yaroslaww-1 commented on backend/src/adapters/mailer/mailer.adapter.ts
> +        user: this.sender,
Fix - https://github.com/Yaroslaww-1/cte/pull/20

2021-04-15 06:15 UTC, nosovk commented on backend/src/api/guards/auth.guard.ts
> +    const bearer = authorization && authorization.startsWith('BEARER ') ? authorization : null;
authorization?.startsWith

2021-04-15 06:16 UTC, nosovk commented on backend/src/api/guards/auth.guard.ts
> +    const token = bearer ? bearer.split('BEARER ')[1] : null;
token = bearer?.split

2021-04-22 14:04 UTC, merged