Feature: Editor component
Yaroslaww-1/cte pull request #22
Opened 2021-04-08 16:59 UTC by Fireman9

2021-04-26 07:55 UTC, Yaroslaww-1 requested changes

2021-04-26 07:55 UTC, Yaroslaww-1 commented on cte-shared/DMP.ts
> +	diff_main(text1: string, text2: string): Diff[] {
rename methods to camelCase => diffMain

2021-04-26 07:55 UTC, Yaroslaww-1 commented on frontend/src/Editor/Button.vue
> +<template>
Move this component to src>conponents>buttons>icon-button

2021-04-26 07:55 UTC, Yaroslaww-1 commented on frontend/src/Editor/Button.vue
> +		@click="if (this.$parent !== null) this.$parent.execute(action);"
use @click="onClick"

2021-04-26 07:55 UTC, Yaroslaww-1 commented on frontend/src/Editor/Button.vue
> +		action: String,
onClick: Function,

2021-04-26 07:55 UTC, Yaroslaww-1 commented on frontend/src/Editor/Editor.vue
> +	execute(command: string, arg?: string): void {
I think its ok to store buttons config inside this file in computed properties (we will get rid of long icon svg string in future). So this method is no longer needed (it is replaced by two onClick methods)

2021-04-26 21:43 UTC, nosovk commented on frontend/src/Editor/Editor.vue
> +	<div id="editor" contenteditable spellcheck="false" @input="this.update">Enter text here...</div>
contenteditable - это супер решение :)

2021-04-26 21:44 UTC, nosovk commented on frontend/src/Editor/Editor.vue
> +import PatchMakeWorker from 'worker-loader!./patch-make.worker';
помоему такая нотация с 5м вебпаком не работает, но не уверен

2021-04-26 21:47 UTC, nosovk commented on frontend/src/Editor/Editor.vue
> +	min-height: 90vh;
https://developer.mozilla.org/en-US/docs/Web/CSS/clamp()

2021-04-26 21:47 UTC, nosovk commented on frontend/src/Editor/modules/italic.ts
> +		'<svg width="1792" height="1792" viewBox="0 0 1792 1792" xmlns="http://www.w3.org/2000/svg"><path d="M384 1662l17-85q6-2 81.5-21.5t111.5-37.5q28-35 41-101 1-7 62-289t114-543.5 52-296.5v-25q-24-13-5
svg все же лучше в виде отдельных файлов хранить

2021-04-26 21:50 UTC, nosovk commented on frontend/package.json
>      "node-sass": "^4.12.0",
его депрекейтнули, вместо него теперь обычный `sass`

2021-04-26 21:51 UTC, nosovk commented on frontend/package.json
> +    "worker-loader": "^3.0.8"
это dev dep, она в проде никак себя не проявляет, т.к. это кусок вебпака

2021-04-28 10:48 UTC, Yaroslaww-1 commented on frontend/package.json
>      "node-sass": "^4.12.0",
Will be fixed in another PR

2021-04-29 07:58 UTC, merged